_prefs: 
  mapid: wprenison.dae404bd
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 15.293
  - 50.8476
  - 4
description: A monotone basemap that's easy to recolor.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Light GoMetro Live
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5,wprenison.b4afb90b"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - stops.mss
  - earthquakes.mss
template: ''
